import SettingsAdvanced from '@/features/settings/advanced';
import BitTorrentSettings from '@/features/settings/bittorrent';
import ConnectionSettings from '@/features/settings/connection';
import DownloadSettings from '@/features/settings/downloads';
import SettingsRss from '@/features/settings/rss';
import SpeedSettings from '@/features/settings/speed';
import SettingsWebUI from '@/features/settings/webui';
import {
  Download,
  Gauge,
  Globe,
  Monitor,
  RssIcon,
  Settings,
  Share2,
} from 'lucide-react';

export interface SettingsSection {
  id: string;
  title: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  component: React.ComponentType;
  keywords: string[];
}

export interface SettingsCategory {
  id: string;
  title: string;
  description: string;
  sections: SettingsSection[];
}

export const settingsCategories: Array<SettingsCategory> = [
  {
    id: 'core',
    title: 'Core Settings',
    description: 'Essential qBittorrent configuration',
    sections: [
      {
        id: 'downloads',
        title: 'Downloads',
        description: 'Download paths, behavior, and file management',
        icon: Download,
        component: DownloadSettings,
        keywords: [
          'download',
          'path',
          'save',
          'folder',
          'directory',
          'temp',
          'temporary',
          'incomplete',
          'finished',
          'auto',
          'management',
          'tmm',
          'category',
          'subfolder',
          'paused',
          'delete',
          'torrent',
          'files',
          'preallocate',
          'extension',
          'organization',
          'structure',
          'location',
          'destination',
          'move',
          'completion',
          'finished',
          'done',
          'storage',
          'disk',
          'space',
          'allocation',
          'sequential',
          'resume',
          'data',
          'file',
          'management',
          'automatic',
          'manual',
          'behavior',
          'options',
          'preferences',
        ],
      },
      {
        id: 'connection',
        title: 'Connection',
        description: 'Network settings, ports, and proxy configuration',
        icon: Globe,
        component: ConnectionSettings,
        keywords: [
          'connection',
          'network',
          'port',
          'listen',
          'upnp',
          'nat',
          'pmp',
          'random',
          'proxy',
          'socks',
          'http',
          'authentication',
          'username',
          'password',
          'peer',
          'rss',
          'hostname',
          'lookup',
          'firewall',
          'router',
          'ip',
          'address',
          'ipv4',
          'ipv6',
          'protocol',
          'tcp',
          'udp',
          'utp',
          'encryption',
          'incoming',
          'outgoing',
          'limit',
          'connections',
          'peers',
          'bandwidth',
          'speed',
          'throttle',
          'rate',
          'networking',
          'internet',
          'local',
          'lan',
          'wan',
          'gateway',
          'dns',
          'dhcp',
          'static',
          'dynamic',
          'configuration',
          'setup',
          'options',
          'preferences',
        ],
      },
      {
        id: 'speed',
        title: 'Speed',
        description: 'Speed limits, scheduling, and bandwidth management',
        icon: Gauge,
        component: SpeedSettings,
        keywords: [
          'speed',
          'limit',
          'bandwidth',
          'download',
          'upload',
          'alternative',
          'alternate',
          'scheduler',
          'schedule',
          'time',
          'hour',
          'minute',
          'days',
          'weekday',
          'weekend',
          'global',
          'rate',
          'throttle',
          'global',
          'limits',
          'unlimited',
          'maximum',
          'minimum',
          'kbps',
          'mbps',
          'bandwidth',
          'allocation',
          'priority',
          'traffic',
          'control',
          'management',
          'scheduling',
          'timetable',
          'automatic',
          'manual',
          'peak',
          'off-peak',
          'hours',
          'period',
          'interval',
          'configuration',
          'setup',
          'options',
          'preferences',
        ],
      },
    ],
  },
  {
    id: 'protocol',
    title: 'Protocol Settings',
    description: 'BitTorrent protocol and advanced networking',
    sections: [
      {
        id: 'bittorrent',
        title: 'BitTorrent',
        description: 'BitTorrent protocol settings and peer management',
        icon: Share2,
        component: BitTorrentSettings,
        keywords: [
          'bittorrent',
          'protocol',
          'dht',
          'pex',
          'peer',
          'exchange',
          'lsd',
          'local',
          'discovery',
          'encryption',
          'active',
          'downloads',
          'uploads',
          'torrents',
          'slow',
          'threshold',
          'ratio',
          'seeding',
          'time',
          'share',
          'limit',
          'action',
          'pause',
          'remove',
          'choking',
          'algorithm',
          'slots',
          'utp',
          'tcp',
          'mixed',
          'mode',
          'tracker',
          'announce',
          'scrape',
          'interval',
          'reannounce',
          'force',
          'start',
          'stop',
          'seed',
          'leech',
          'upload',
          'download',
          'ratio',
          'sharing',
          'super',
          'seeding',
          'initial',
          'piece',
          'rarest',
          'first',
          'random',
          'full',
          'end',
          'verification',
          'checking',
          'hash',
          'integrity',
          'magnet',
          'link',
          'uri',
          'metadata',
          'extension',
          'protocol',
          'bep',
          'specification',
          'configuration',
          'setup',
          'options',
          'preferences',
        ],
      },
    ],
  },
  {
    id: 'content',
    title: 'Content Settings',
    description: 'RSS feeds and content management',
    sections: [
      {
        id: 'rss',
        title: 'RSS',
        description: 'RSS feed settings and automatic torrent downloading',
        icon: RssIcon,
        component: SettingsRss,
        keywords: [
          'rss',
          'feed',
          'feeds',
          'automatic',
          'auto',
          'download',
          'downloading',
          'torrent',
          'torrents',
          'reader',
          'fetch',
          'fetching',
          'refresh',
          'interval',
          'delay',
          'request',
          'host',
          'articles',
          'items',
          'max',
          'maximum',
          'repack',
          'proper',
          'episode',
          'filter',
          'filters',
          'smart',
          'regex',
          'pattern',
          'patterns',
          'rule',
          'rules',
          'automation',
          'automatic',
          'scheduler',
          'scheduling',
          'content',
          'management',
          'subscription',
          'subscriptions',
          'podcast',
          'podcasts',
          'news',
          'blog',
          'blogs',
          'xml',
          'atom',
          'syndication',
          'notification',
          'notifications',
          'alert',
          'alerts',
          'trigger',
          'triggers',
          'action',
          'actions',
          'processing',
          'enabled',
          'disabled',
          'active',
          'inactive',
          'configuration',
          'setup',
          'options',
          'preferences',
        ],
      },
    ],
  },
  {
    id: 'interface',
    title: 'Interface Settings',
    description: 'Web UI customization and user preferences',
    sections: [
      {
        id: 'web-ui',
        title: 'Web UI',
        description: 'Web interface settings and customization',
        icon: Monitor,
        component: SettingsWebUI,
        keywords: [
          'webui',
          'web-ui',
          'web',
          'ui',
          'interface',
          'theme',
          'dark',
          'light',
          'language',
          'compact',
          'mode',
          'columns',
          'table',
          'sort',
          'refresh',
          'interval',
          'notifications',
          'sound',
          'desktop',
          'confirm',
          'deletion',
          'advanced',
          'settings',
          'appearance',
          'display',
          'layout',
          'design',
          'customization',
          'personalization',
          'user',
          'experience',
          'ux',
          'locale',
          'internationalization',
          'i18n',
          'localization',
          'responsive',
          'mobile',
          'tablet',
          'desktop',
          'resolution',
          'scaling',
          'zoom',
          'font',
          'size',
          'color',
          'scheme',
          'accent',
          'primary',
          'secondary',
          'background',
          'foreground',
          'alternative',
          'contrast',
          'high',
          'low',
          'accessibility',
          'a11y',
          'keyboard',
          'navigation',
          'shortcuts',
          'hotkeys',
          'gestures',
          'touch',
          'click',
          'hover',
          'focus',
          'tab',
          'order',
          'breadcrumbs',
          'navigation',
          'menu',
          'toolbar',
          'status',
          'bar',
          'footer',
          'header',
          'sidebar',
          'panel',
          'widget',
          'component',
          'element',
          'refresh',
          'reload',
          'update',
          'real-time',
          'live',
          'dynamic',
          'interactive',
          'responsive',
          'fast',
          'smooth',
          'performance',
          'optimization',
          'cache',
          'caching',
          'storage',
          'local',
          'session',
          'cookie',
          'cookies',
          'privacy',
          'security',
          'authentication',
          'authorization',
          'login',
          'logout',
          'session',
          'timeout',
          'ban',
          'duration',
          'attempts',
          'failure',
          'clickjacking',
          'protection',
          'csrf',
          'cross-site',
          'request',
          'forgery',
          'secure',
          'https',
          'ssl',
          'tls',
          'certificate',
          'certificates',
          'reverse',
          'proxy',
          'headers',
          'custom',
          'host',
          'validation',
          'configuration',
          'setup',
          'options',
          'preferences',
        ],
      },
    ],
  },
  {
    id: 'advanced',
    title: 'Advanced Settings',
    description: 'Expert configuration and system settings',
    sections: [
      {
        id: 'advanced',
        title: 'Advanced',
        description: 'Advanced qBittorrent configuration for experts',
        icon: Settings,
        component: SettingsAdvanced,
        keywords: [
          'advanced',
          'expert',
          'resume',
          'data',
          'storage',
          'queueing',
          'checking',
          'disk',
          'cache',
          'ttl',
          'io',
          'mode',
          'type',
          'os',
          'coalesce',
          'reads',
          'writes',
          'piece',
          'extent',
          'affinity',
          'upload',
          'suggestions',
          'buffer',
          'watermark',
          'factor',
          'connection',
          'speed',
          'socket',
          'backlog',
          'outgoing',
          'ports',
          'min',
          'max',
          'utp',
          'rate',
          'limited',
          'embedded',
          'tracker',
          'updates',
          'icon',
          'theme',
          'logging',
          'log',
          'level',
          'file',
          'backup',
          'size',
          'delete',
          'old',
          'age',
          'performance',
          'warning',
          'behavior',
          'confirm',
          'torrent',
          'deletion',
          'recheck',
          'remove',
          'tags',
          'ipv6',
          'announce',
          'trackers',
          'tier',
          'tiers',
          'ip',
          'stop',
          'condition',
          'merge',
          'scan',
          'directories',
          'export',
          'directory',
          'mail',
          'notification',
          'email',
          'sender',
          'smtp',
          'ssl',
          'auth',
          'autorun',
          'external',
          'program',
          'completion',
          'expert',
          'professional',
          'developer',
          'power',
          'user',
          'technical',
          'system',
          'low-level',
          'kernel',
          'os',
          'operating',
          'system',
          'memory',
          'ram',
          'virtual',
          'physical',
          'hardware',
          'cpu',
          'processor',
          'cores',
          'threads',
          'multithreading',
          'parallel',
          'concurrent',
          'asynchronous',
          'async',
          'synchronous',
          'sync',
          'blocking',
          'non-blocking',
          'io',
          'input',
          'output',
          'read',
          'write',
          'sequential',
          'random',
          'direct',
          'buffered',
          'unbuffered',
          'streaming',
          'stream',
          'pipeline',
          'pipelining',
          'queue',
          'queuing',
          'fifo',
          'lifo',
          'priority',
          'scheduling',
          'scheduler',
          'round-robin',
          'weighted',
          'fair',
          'preemptive',
          'cooperative',
          'context',
          'switch',
          'switching',
          'interrupt',
          'interrupts',
          'signal',
          'signals',
          'event',
          'events',
          'callback',
          'callbacks',
          'handler',
          'handlers',
          'hook',
          'hooks',
          'plugin',
          'plugins',
          'extension',
          'extensions',
          'module',
          'modules',
          'library',
          'libraries',
          'api',
          'sdk',
          'framework',
          'runtime',
          'environment',
          'vm',
          'virtual',
          'machine',
          'jit',
          'just-in-time',
          'compilation',
          'compiling',
          'interpreter',
          'interpreted',
          'compiled',
          'native',
          'binary',
          'executable',
          'debug',
          'debugging',
          'trace',
          'tracing',
          'profile',
          'profiling',
          'benchmark',
          'benchmarking',
          'test',
          'testing',
          'unit',
          'integration',
          'end-to-end',
          'e2e',
          'automation',
          'automated',
          'ci',
          'cd',
          'continuous',
          'deployment',
          'delivery',
          'devops',
          'agile',
          'scrum',
          'kanban',
          'waterfall',
          'methodology',
          'process',
          'workflow',
          'pipeline',
          'build',
          'compile',
          'package',
          'packaging',
          'distribution',
          'distro',
          'repository',
          'repo',
          'version',
          'control',
          'vcs',
          'git',
          'svn',
          'mercurial',
          'hg',
          'bzr',
          'cvs',
          'perforce',
          'clearcase',
          'tfs',
          'team',
          'foundation',
          'server',
          'client',
          'daemon',
          'service',
          'background',
          'foreground',
          'process',
          'thread',
          'task',
          'job',
          'worker',
          'pool',
          'cluster',
          'grid',
          'cloud',
          'distributed',
          'parallel',
          'concurrent',
          'scalable',
          'scalability',
          'elastic',
          'fault-tolerant',
          'redundant',
          'high-availability',
          'ha',
          'disaster',
          'recovery',
          'backup',
          'restore',
          'snapshot',
          'checkpoint',
          'rollback',
          'transaction',
          'acid',
          'consistency',
          'isolation',
          'durability',
          'lock',
          'locking',
          'mutex',
          'semaphore',
          'condition',
          'variable',
          'atomic',
          'volatile',
          'memory',
          'barrier',
          'fence',
          'cache',
          'coherence',
          'coherency',
          'invalidation',
          'eviction',
          'replacement',
          'policy',
          'lru',
          'lfu',
          'fifo',
          'random',
          'optimal',
          'belady',
          'paging',
          'segmentation',
          'virtual',
          'address',
          'physical',
          'address',
          'translation',
          'tlb',
          'page',
          'table',
          'segment',
          'descriptor',
          'register',
          'flag',
          'bit',
          'byte',
          'word',
          'dword',
          'qword',
          'endian',
          'endianness',
          'big-endian',
          'little-endian',
          'network',
          'byte',
          'order',
          'alignment',
          'padding',
          'packing',
          'marshaling',
          'serialization',
          'deserialization',
          'encoding',
          'decoding',
          'compression',
          'decompression',
          'encryption',
          'decryption',
          'hash',
          'checksum',
          'crc',
          'md5',
          'sha1',
          'sha256',
          'sha512',
          'aes',
          'rsa',
          'ecc',
          'elliptic',
          'curve',
          'diffie-hellman',
          'dh',
          'key',
          'exchange',
          'digital',
          'signature',
          'certificate',
          'ca',
          'pki',
          'public',
          'private',
          'asymmetric',
          'symmetric',
          'cipher',
          'block',
          'stream',
          'mode',
          'cbc',
          'ecb',
          'cfb',
          'ofb',
          'ctr',
          'gcm',
          'ccm',
          'xts',
          'authentication',
          'authorization',
          'access',
          'control',
          'rbac',
          'abac',
          'policy',
          'audit',
          'logging',
          'monitoring',
          'observability',
          'telemetry',
          'metrics',
          'statistics',
          'analytics',
          'reporting',
          'dashboard',
          'visualization',
          'chart',
          'graph',
          'plot',
          'diagram',
          'uml',
          'erd',
          'erd',
          'schema',
          'database',
          'db',
          'sql',
          'nosql',
          'document',
          'key-value',
          'column-family',
          'wide-column',
          'graph',
          'time-series',
          'newsql',
          'acid',
          'base',
          'cap',
          'theorem',
          'consistency',
          'availability',
          'partition',
          'tolerance',
          'replication',
          'sharding',
          'partitioning',
          'horizontal',
          'vertical',
          'scaling',
          'load',
          'balancing',
          'failover',
          'circuit',
          'breaker',
          'retry',
          'timeout',
          'deadline',
          'cancellation',
          'graceful',
          'shutdown',
          'startup',
          'initialization',
          'configuration',
          'setup',
          'options',
          'preferences',
        ],
      },
    ],
  },
];

export interface SearchResult {
  section: SettingsSection;
  category: SettingsCategory;
  matchType: 'title' | 'description' | 'keyword';
  matchText: string;
  highlightedText?: string;
}

// Utility function to search settings
export function searchSettings(query: string): Array<SearchResult> {
  const results: Array<SearchResult & { score: number }> = [];

  const searchTerm = query.toLowerCase().trim();
  if (!searchTerm) return [];

  settingsCategories.forEach((category) => {
    category.sections.forEach((section) => {
      let score = 0;
      let matchType: 'title' | 'description' | 'keyword' | null = null;
      let matchText = '';
      let highlightedText: string | undefined;

      // Check title match - highest score
      if (section.title.toLowerCase().includes(searchTerm)) {
        // Highlight the matching text in the title
        highlightedText = section.title.replace(
          new RegExp(`(${searchTerm})`, 'gi'),
          '<mark>$1</mark>'
        );
        score += 100; // High score for title matches
        matchType = 'title';
        matchText = section.title;
      }

      // Check description match - medium score
      if (section.description.toLowerCase().includes(searchTerm)) {
        // Highlight the matching text in the description
        const highlightedDescription = section.description.replace(
          new RegExp(`(${searchTerm})`, 'gi'),
          '<mark>$1</mark>'
        );
        score += 50; // Medium score for description matches
        if (!matchType) {
          // Only set if not already matched by title
          matchType = 'description';
          matchText = section.description;
          highlightedText = highlightedDescription;
        }
      }

      // Check keyword matches - lower score per keyword
      const matchingKeywords = section.keywords.filter((keyword) =>
        keyword.toLowerCase().includes(searchTerm)
      );

      if (matchingKeywords.length > 0) {
        score += matchingKeywords.length * 10; // 10 points per matching keyword
        if (!matchType) {
          // Only set if not already matched by title or description
          matchType = 'keyword';
          matchText = matchingKeywords[0]; // Use the first matching keyword
        }
      }

      // Add to results if we have any matches
      if (score > 0 && matchType) {
        results.push({
          section,
          category,
          matchType,
          matchText,
          highlightedText,
          score,
        });
      }
    });
  });

  // Sort results by score (highest first)
  results.sort((a, b) => b.score - a.score);

  // Remove the score property before returning
  return results.map(({ score: _score, ...rest }) => rest);
}
