/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRssRouteImport } from './routes/_authenticated/rss'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTorrentsIndexRouteImport } from './routes/_authenticated/torrents/index'
import { Route as AuthenticatedTorrentsHashRouteImport } from './routes/_authenticated/torrents/$hash'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRssRoute = AuthenticatedRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTorrentsIndexRoute =
  AuthenticatedTorrentsIndexRouteImport.update({
    id: '/torrents/',
    path: '/torrents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTorrentsHashRoute =
  AuthenticatedTorrentsHashRouteImport.update({
    id: '/torrents/$hash',
    path: '/torrents/$hash',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rss': typeof AuthenticatedRssRoute
  '/search': typeof AuthenticatedSearchRoute
  '/torrents/$hash': typeof AuthenticatedTorrentsHashRoute
  '/torrents': typeof AuthenticatedTorrentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rss': typeof AuthenticatedRssRoute
  '/search': typeof AuthenticatedSearchRoute
  '/torrents/$hash': typeof AuthenticatedTorrentsHashRoute
  '/torrents': typeof AuthenticatedTorrentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rss': typeof AuthenticatedRssRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/torrents/$hash': typeof AuthenticatedTorrentsHashRoute
  '/_authenticated/torrents/': typeof AuthenticatedTorrentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/rss'
    | '/search'
    | '/torrents/$hash'
    | '/torrents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/rss'
    | '/search'
    | '/torrents/$hash'
    | '/torrents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/rss'
    | '/_authenticated/search'
    | '/_authenticated/torrents/$hash'
    | '/_authenticated/torrents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rss': {
      id: '/_authenticated/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof AuthenticatedRssRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/torrents/': {
      id: '/_authenticated/torrents/'
      path: '/torrents'
      fullPath: '/torrents'
      preLoaderRoute: typeof AuthenticatedTorrentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/torrents/$hash': {
      id: '/_authenticated/torrents/$hash'
      path: '/torrents/$hash'
      fullPath: '/torrents/$hash'
      preLoaderRoute: typeof AuthenticatedTorrentsHashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRssRoute: typeof AuthenticatedRssRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTorrentsHashRoute: typeof AuthenticatedTorrentsHashRoute
  AuthenticatedTorrentsIndexRoute: typeof AuthenticatedTorrentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRssRoute: AuthenticatedRssRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTorrentsHashRoute: AuthenticatedTorrentsHashRoute,
  AuthenticatedTorrentsIndexRoute: AuthenticatedTorrentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
