/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRssRouteImport } from './routes/_authenticated/rss'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTorrentsIndexRouteImport } from './routes/_authenticated/torrents/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedTorrentsHashRouteImport } from './routes/_authenticated/torrents/$hash'
import { Route as AuthenticatedSettingsWebuiRouteImport } from './routes/_authenticated/settings/webui'
import { Route as AuthenticatedSettingsSpeedRouteImport } from './routes/_authenticated/settings/speed'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDownloadsRouteImport } from './routes/_authenticated/settings/downloads'
import { Route as AuthenticatedSettingsConnectionRouteImport } from './routes/_authenticated/settings/connection'
import { Route as AuthenticatedSettingsBittorrentRouteImport } from './routes/_authenticated/settings/bittorrent'
import { Route as AuthenticatedSettingsAdvancedRouteImport } from './routes/_authenticated/settings/advanced'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRssRoute = AuthenticatedRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTorrentsIndexRoute =
  AuthenticatedTorrentsIndexRouteImport.update({
    id: '/torrents/',
    path: '/torrents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTorrentsHashRoute =
  AuthenticatedTorrentsHashRouteImport.update({
    id: '/torrents/$hash',
    path: '/torrents/$hash',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWebuiRoute =
  AuthenticatedSettingsWebuiRouteImport.update({
    id: '/settings/webui',
    path: '/settings/webui',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSpeedRoute =
  AuthenticatedSettingsSpeedRouteImport.update({
    id: '/settings/speed',
    path: '/settings/speed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDownloadsRoute =
  AuthenticatedSettingsDownloadsRouteImport.update({
    id: '/settings/downloads',
    path: '/settings/downloads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsConnectionRoute =
  AuthenticatedSettingsConnectionRouteImport.update({
    id: '/settings/connection',
    path: '/settings/connection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBittorrentRoute =
  AuthenticatedSettingsBittorrentRouteImport.update({
    id: '/settings/bittorrent',
    path: '/settings/bittorrent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAdvancedRoute =
  AuthenticatedSettingsAdvancedRouteImport.update({
    id: '/settings/advanced',
    path: '/settings/advanced',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/rss': typeof AuthenticatedRssRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/settings/bittorrent': typeof AuthenticatedSettingsBittorrentRoute
  '/settings/connection': typeof AuthenticatedSettingsConnectionRoute
  '/settings/downloads': typeof AuthenticatedSettingsDownloadsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/speed': typeof AuthenticatedSettingsSpeedRoute
  '/settings/webui': typeof AuthenticatedSettingsWebuiRoute
  '/torrents/$hash': typeof AuthenticatedTorrentsHashRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/torrents': typeof AuthenticatedTorrentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/rss': typeof AuthenticatedRssRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/settings/bittorrent': typeof AuthenticatedSettingsBittorrentRoute
  '/settings/connection': typeof AuthenticatedSettingsConnectionRoute
  '/settings/downloads': typeof AuthenticatedSettingsDownloadsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/speed': typeof AuthenticatedSettingsSpeedRoute
  '/settings/webui': typeof AuthenticatedSettingsWebuiRoute
  '/torrents/$hash': typeof AuthenticatedTorrentsHashRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/torrents': typeof AuthenticatedTorrentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/rss': typeof AuthenticatedRssRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/advanced': typeof AuthenticatedSettingsAdvancedRoute
  '/_authenticated/settings/bittorrent': typeof AuthenticatedSettingsBittorrentRoute
  '/_authenticated/settings/connection': typeof AuthenticatedSettingsConnectionRoute
  '/_authenticated/settings/downloads': typeof AuthenticatedSettingsDownloadsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/speed': typeof AuthenticatedSettingsSpeedRoute
  '/_authenticated/settings/webui': typeof AuthenticatedSettingsWebuiRoute
  '/_authenticated/torrents/$hash': typeof AuthenticatedTorrentsHashRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/torrents/': typeof AuthenticatedTorrentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/logs'
    | '/rss'
    | '/search'
    | '/settings/account'
    | '/settings/advanced'
    | '/settings/bittorrent'
    | '/settings/connection'
    | '/settings/downloads'
    | '/settings/notifications'
    | '/settings/speed'
    | '/settings/webui'
    | '/torrents/$hash'
    | '/settings'
    | '/torrents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/logs'
    | '/rss'
    | '/search'
    | '/settings/account'
    | '/settings/advanced'
    | '/settings/bittorrent'
    | '/settings/connection'
    | '/settings/downloads'
    | '/settings/notifications'
    | '/settings/speed'
    | '/settings/webui'
    | '/torrents/$hash'
    | '/settings'
    | '/torrents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/logs'
    | '/_authenticated/rss'
    | '/_authenticated/search'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/advanced'
    | '/_authenticated/settings/bittorrent'
    | '/_authenticated/settings/connection'
    | '/_authenticated/settings/downloads'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/speed'
    | '/_authenticated/settings/webui'
    | '/_authenticated/torrents/$hash'
    | '/_authenticated/settings/'
    | '/_authenticated/torrents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rss': {
      id: '/_authenticated/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof AuthenticatedRssRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/torrents/': {
      id: '/_authenticated/torrents/'
      path: '/torrents'
      fullPath: '/torrents'
      preLoaderRoute: typeof AuthenticatedTorrentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/torrents/$hash': {
      id: '/_authenticated/torrents/$hash'
      path: '/torrents/$hash'
      fullPath: '/torrents/$hash'
      preLoaderRoute: typeof AuthenticatedTorrentsHashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/webui': {
      id: '/_authenticated/settings/webui'
      path: '/settings/webui'
      fullPath: '/settings/webui'
      preLoaderRoute: typeof AuthenticatedSettingsWebuiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/speed': {
      id: '/_authenticated/settings/speed'
      path: '/settings/speed'
      fullPath: '/settings/speed'
      preLoaderRoute: typeof AuthenticatedSettingsSpeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/downloads': {
      id: '/_authenticated/settings/downloads'
      path: '/settings/downloads'
      fullPath: '/settings/downloads'
      preLoaderRoute: typeof AuthenticatedSettingsDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/connection': {
      id: '/_authenticated/settings/connection'
      path: '/settings/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/bittorrent': {
      id: '/_authenticated/settings/bittorrent'
      path: '/settings/bittorrent'
      fullPath: '/settings/bittorrent'
      preLoaderRoute: typeof AuthenticatedSettingsBittorrentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/advanced': {
      id: '/_authenticated/settings/advanced'
      path: '/settings/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof AuthenticatedSettingsAdvancedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedRssRoute: typeof AuthenticatedRssRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAdvancedRoute: typeof AuthenticatedSettingsAdvancedRoute
  AuthenticatedSettingsBittorrentRoute: typeof AuthenticatedSettingsBittorrentRoute
  AuthenticatedSettingsConnectionRoute: typeof AuthenticatedSettingsConnectionRoute
  AuthenticatedSettingsDownloadsRoute: typeof AuthenticatedSettingsDownloadsRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSpeedRoute: typeof AuthenticatedSettingsSpeedRoute
  AuthenticatedSettingsWebuiRoute: typeof AuthenticatedSettingsWebuiRoute
  AuthenticatedTorrentsHashRoute: typeof AuthenticatedTorrentsHashRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTorrentsIndexRoute: typeof AuthenticatedTorrentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedRssRoute: AuthenticatedRssRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAdvancedRoute: AuthenticatedSettingsAdvancedRoute,
  AuthenticatedSettingsBittorrentRoute: AuthenticatedSettingsBittorrentRoute,
  AuthenticatedSettingsConnectionRoute: AuthenticatedSettingsConnectionRoute,
  AuthenticatedSettingsDownloadsRoute: AuthenticatedSettingsDownloadsRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsSpeedRoute: AuthenticatedSettingsSpeedRoute,
  AuthenticatedSettingsWebuiRoute: AuthenticatedSettingsWebuiRoute,
  AuthenticatedTorrentsHashRoute: AuthenticatedTorrentsHashRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTorrentsIndexRoute: AuthenticatedTorrentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
